# Ce fichier définit comment Logstash reçoit, traite et stocke les logs.
# input : écoute les logs JSON envoyés par les services Spring Boot sur le port TCP 5000.
# filter : décode le JSON automatiquement (déjà géré par LogstashEncoder).
# output : indexe chaque log dans Elasticsearch avec un index horodaté.
input {
    tcp {
        port => 5000
        codec => json_lines
    }
}
output {
    elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "microservices-logs-%{+YYYY.MM.dd}"
    }
}
