apiVersion: apps/v1
kind: Deployment
metadata:
  name: grading-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grading-service
  template:
    metadata:
      labels:
        app: grading-service
    spec:
      containers:
        - name: grading-service
          image: sen5e1/projet-etudiants-grading-service:2.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/etudiantsdb
            - name: CLIENTS_ETUDIANT_SERVICE_URL
              value: http://etudiant-service:8081