apiVersion: v1
kind: Service

metadata:
  name: postgres # Ce nom est utilisé comme hostname par les autres services

spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432

  type: ClusterIP # Accessible uniquement depuis l'intérieur du cluster